# Generated by Django 2.1.7 on 2021-06-11 18:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_delete_counties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_code', models.CharField(max_length=254)),
                ('bst', models.IntegerField()),
                ('use', models.IntegerField()),
                ('soc', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
    ]
