# Generated by Django 2.1.7 on 2021-06-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_counties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counties',
        ),
    ]
