# Generated by Django 2.1.7 on 2021-06-11 20:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0009_delete_counties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=254)),
                ('province_c', models.FloatField()),
                ('district', models.CharField(max_length=254)),
                ('district_c', models.IntegerField()),
                ('remarks', models.CharField(max_length=254)),
                ('m_20110324', models.IntegerField()),
                ('d_name', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
    ]
